import {
  Combine,
  Scissors,
  Minimize2,
  FileText,
  Presentation,
  Table2,
  PenLine,
  Images,
  ImagePlus,
  Signature,
  Droplets,
  RotateCw,
  Code2,
  LockKeyhole,
  UnlockKeyhole,
  LayoutGrid,
  Archive,
  HeartPulse,
  ListOrdered,
  ScanLine,
  ScanText,
  Columns2,
  RectangleEllipsis,
  Crop,
  TextCursorInput,
  Sparkles,
  Languages,
  FileCode2,
  FileMinus2,
  Files,
  Layers,
  FolderDown,
} from "lucide-react";
const icons: Record<string, typeof FileText> = {
  merge: Combine,
  split: Scissors,
  compress: Minimize2,
  word: FileText,
  presentation: Presentation,
  sheet: Table2,
  edit: PenLine,
  image: Images,
  imageplus: ImagePlus,
  sign: Signature,
  watermark: Droplets,
  rotate: RotateCw,
  code: Code2,
  lock: LockKeyhole,
  unlock: UnlockKeyhole,
  organize: LayoutGrid,
  archive: Archive,
  repair: HeartPulse,
  numbers: ListOrdered,
  scan: ScanLine,
  ocr: ScanText,
  compare: Columns2,
  redact: RectangleEllipsis,
  crop: Crop,
  forms: TextCursorInput,
  sparkles: Sparkles,
  languages: Languages,
  markdown: FileCode2,
  remove: FileMinus2,
  extract: Files,
};
export function ToolIcon({
  name,
  size = 25,
  className = "",
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const Icon = icons[name] || FileText;
  return <Icon size={size} strokeWidth={1.65} className={className} />;
}
export const categoryIcons: Record<string, typeof FileText> = {
  "All tools": LayoutGrid,
  Organize: Layers,
  Optimize: Minimize2,
  Convert: FolderDown,
  Edit: PenLine,
  Security: LockKeyhole,
  Intelligence: Sparkles,
};
