export type Category =
  | "All tools"
  | "Organize"
  | "Optimize"
  | "Convert"
  | "Edit"
  | "Security"
  | "Intelligence";
export type Tool = {
  id: string;
  name: string;
  description: string;
  category: Category;
  icon: string;
  color: string;
  engine: "local" | "render" | "service";
  accept: string;
  multiple?: boolean;
  badge?: string;
  note?: string;
};
const pdf = ".pdf";
export const tools: Tool[] = [
  {
    id: "merge-pdf",
    name: "Merge PDF",
    description: "Good things come together. Combine your PDFs into one.",
    category: "Organize",
    icon: "merge",
    color: "red",
    engine: "local",
    accept: pdf,
    multiple: true,
    badge: "Popular",
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    description: "A page, a chapter, or something in between. Make the cut.",
    category: "Organize",
    icon: "split",
    color: "orange",
    engine: "local",
    accept: pdf,
  },
  {
    id: "compress-pdf",
    name: "Compress PDF",
    description: "Less size. More possibility. Lighten your documents.",
    category: "Optimize",
    icon: "compress",
    color: "green",
    engine: "render",
    accept: pdf,
    badge: "Popular",
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description: "From final draft to fresh start. Make your text editable.",
    category: "Convert",
    icon: "word",
    color: "blue",
    engine: "render",
    accept: pdf,
    note: "Exports editable text in reading order. Original page layout, images, and tables are not preserved.",
  },
  {
    id: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    description: "Give your document a stage. Turn pages into slides.",
    category: "Convert",
    icon: "presentation",
    color: "orange",
    engine: "render",
    accept: pdf,
    note: "Each page becomes a high-quality slide image; individual objects are not editable.",
  },
  {
    id: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Take your data further. Move PDF text into a spreadsheet.",
    category: "Convert",
    icon: "sheet",
    color: "green",
    engine: "render",
    accept: pdf,
    note: "Exports detected text lines into spreadsheet rows. Review columns after conversion.",
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    description: "Keep every word in place, on every screen.",
    category: "Convert",
    icon: "word",
    color: "blue",
    engine: "service",
    accept: ".doc,.docx",
  },
  {
    id: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    description: "Your presentation, beautifully preserved and ready to share.",
    category: "Convert",
    icon: "presentation",
    color: "orange",
    engine: "service",
    accept: ".ppt,.pptx",
  },
  {
    id: "excel-to-pdf",
    name: "Excel to PDF",
    description: "Give your spreadsheets a clean, shareable finish.",
    category: "Convert",
    icon: "sheet",
    color: "green",
    engine: "service",
    accept: ".xls,.xlsx",
  },
  {
    id: "edit-pdf",
    name: "Edit PDF",
    description: "Add your words. Leave your mark. Make it yours.",
    category: "Edit",
    icon: "edit",
    color: "purple",
    engine: "local",
    accept: pdf,
    note: "Add text annotations. Editing existing text, shapes, and freehand annotations are planned.",
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "A new perspective. Turn each page into a crisp image.",
    category: "Convert",
    icon: "image",
    color: "yellow",
    engine: "render",
    accept: pdf,
  },
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Your images, all on the same page. Create a PDF.",
    category: "Convert",
    icon: "imageplus",
    color: "yellow",
    engine: "local",
    accept: ".jpg,.jpeg,.png",
    multiple: true,
  },
  {
    id: "sign-pdf",
    name: "Sign PDF",
    description: "Make it official. Add your personal signature in seconds.",
    category: "Security",
    icon: "sign",
    color: "purple",
    engine: "local",
    accept: pdf,
    note: "Adds a visible electronic signature. Certificate-based digital signatures and signature requests require a signing service.",
  },
  {
    id: "watermark",
    name: "Watermark",
    description: "Put your stamp on it. Add text or an image overlay.",
    category: "Edit",
    icon: "watermark",
    color: "teal",
    engine: "local",
    accept: pdf,
  },
  {
    id: "rotate-pdf",
    name: "Rotate PDF",
    description: "Find the right angle. Rotate one page or the whole file.",
    category: "Organize",
    icon: "rotate",
    color: "purple",
    engine: "local",
    accept: pdf,
  },
  {
    id: "html-to-pdf",
    name: "HTML to PDF",
    description: "Save a piece of the web, perfectly packaged.",
    category: "Convert",
    icon: "code",
    color: "blue",
    engine: "service",
    accept: ".html,.htm",
  },
  {
    id: "unlock-pdf",
    name: "Unlock PDF",
    description: "Open up possibilities. Remove a password you know.",
    category: "Security",
    icon: "unlock",
    color: "teal",
    engine: "service",
    accept: pdf,
  },
  {
    id: "protect-pdf",
    name: "Protect PDF",
    description: "For your eyes only. Secure files with AES-256 encryption.",
    category: "Security",
    icon: "lock",
    color: "red",
    engine: "service",
    accept: pdf,
  },
  {
    id: "organize-pdf",
    name: "Organize PDF",
    description:
      "Everything in its right place. Rearrange, rotate, and remove.",
    category: "Organize",
    icon: "organize",
    color: "purple",
    engine: "local",
    accept: pdf,
  },
  {
    id: "pdf-to-pdfa",
    name: "PDF to PDF/A",
    description: "Made to last. Prepare documents for long-term archiving.",
    category: "Convert",
    icon: "archive",
    color: "blue",
    engine: "service",
    accept: pdf,
    note: "Requires an archival conversion service and independent PDF/A validation.",
  },
  {
    id: "repair-pdf",
    name: "Repair PDF",
    description: "Give damaged documents a second chance.",
    category: "Optimize",
    icon: "repair",
    color: "orange",
    engine: "service",
    accept: pdf,
  },
  {
    id: "page-numbers",
    name: "Page numbers",
    description: "Keep your reader on track. Add a little order.",
    category: "Edit",
    icon: "numbers",
    color: "blue",
    engine: "local",
    accept: pdf,
  },
  {
    id: "scan-to-pdf",
    name: "Scan to PDF",
    description: "From paper to possibility. Capture and combine your scans.",
    category: "Organize",
    icon: "scan",
    color: "teal",
    engine: "local",
    accept: ".jpg,.jpeg,.png",
    multiple: true,
    note: "Use your phone camera or select scan images. Cross-device transfer is planned.",
  },
  {
    id: "ocr-pdf",
    name: "OCR PDF",
    description: "Make scanned words searchable, selectable, and useful.",
    category: "Intelligence",
    icon: "ocr",
    color: "purple",
    engine: "render",
    accept: pdf,
    badge: "Smart",
    note: "English recognition runs locally. The recognition model downloads on first use.",
  },
  {
    id: "compare-pdf",
    name: "Compare PDF",
    description: "Spot what changed. Two versions, one clear picture.",
    category: "Edit",
    icon: "compare",
    color: "blue",
    engine: "render",
    accept: pdf,
    multiple: true,
  },
  {
    id: "redact-pdf",
    name: "Redact PDF",
    description: "Keep private details private. Permanently remove an area.",
    category: "Security",
    icon: "redact",
    color: "red",
    engine: "render",
    accept: pdf,
    note: "Renders pages to images and removes the selected region. Text selection and links are lost.",
  },
  {
    id: "crop-pdf",
    name: "Crop PDF",
    description: "Focus on what matters. Trim the edges with precision.",
    category: "Edit",
    icon: "crop",
    color: "teal",
    engine: "local",
    accept: pdf,
    note: "Changes the visible page boundary. Cropped content is still in the file; use Redact for sensitive information.",
  },
  {
    id: "pdf-forms",
    name: "PDF Forms",
    description: "Fill in the blanks. Complete interactive PDF form fields.",
    category: "Edit",
    icon: "forms",
    color: "purple",
    engine: "local",
    accept: pdf,
    badge: "New",
    note: "Fill existing text fields and checkboxes. Form creation and automatic field detection are planned.",
  },
  {
    id: "ai-summarizer",
    name: "AI Summarizer",
    description: "Less reading. More understanding. Get the key ideas.",
    category: "Intelligence",
    icon: "sparkles",
    color: "purple",
    engine: "service",
    accept: pdf,
    badge: "AI",
  },
  {
    id: "translate-pdf",
    name: "Translate PDF",
    description: "Your ideas, without language barriers.",
    category: "Intelligence",
    icon: "languages",
    color: "blue",
    engine: "service",
    accept: pdf,
    badge: "AI",
  },
  {
    id: "pdf-to-markdown",
    name: "PDF to Markdown",
    description: "Clean text for your notes, docs, and next big idea.",
    category: "Convert",
    icon: "markdown",
    color: "slate",
    engine: "render",
    accept: pdf,
    note: "Exports text with page headings. Complex tables and original formatting require review.",
  },
  {
    id: "remove-pages",
    name: "Remove pages",
    description: "A little less is sometimes more. Remove unwanted pages.",
    category: "Organize",
    icon: "remove",
    color: "red",
    engine: "local",
    accept: pdf,
  },
  {
    id: "extract-pages",
    name: "Extract pages",
    description: "Take just what you need. Save selected pages as a PDF.",
    category: "Organize",
    icon: "extract",
    color: "orange",
    engine: "local",
    accept: pdf,
  },
  {
    id: "png-to-pdf",
    name: "PNG to PDF",
    description: "Keep your images sharp in a perfectly arranged document.",
    category: "Convert",
    icon: "imageplus",
    color: "yellow",
    engine: "local",
    accept: ".png,.jpg,.jpeg",
    multiple: true,
  },
  {
    id: "pdf-to-png",
    name: "PDF to PNG",
    description: "Every detail, preserved. Export lossless page images.",
    category: "Convert",
    icon: "image",
    color: "yellow",
    engine: "render",
    accept: pdf,
  },
];
export const categories: Category[] = [
  "All tools",
  "Organize",
  "Optimize",
  "Convert",
  "Edit",
  "Security",
  "Intelligence",
];
export const getTool = (id: string) => tools.find((t) => t.id === id);
